### ISSUE TITLE
Storybook throws an error

### ISSUE THREAD

**Issue by mattdell** [DeloitteDigitalUK/react-redux-starter-app#32]
When running `npm run storybook` the following error is shown in the console

![screen shot 2016-10-26 at 17 11 34](https://cloud.githubusercontent.com/assets/2536442/19734413/54769eb4-9b9f-11e6-92ba-65f15d1d81bc.png)

```
mdell@UK134489 ~/W/R/react-redux-starter-app> npm run storybook

> react-redux-starter-app@0.1.0 storybook /Users/mdell/Work/Repos/react-redux-starter-app
> start-storybook -p 9001

=> Loading custom .babelrc
/Users/mdell/Work/Repos/react-redux-starter-app/.storybook/webpack.config.js:2
let mainWebpackConfig = require('../build/webpack.config.js').default;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at exports.default (/Users/mdell/Work/Repos/react-redux-starter-app/node_modules/@kadira/storybook/dist/server/config.js:67:22)
    at exports.default (/Users/mdell/Work/Repos/react-redux-starter-app/node_modules/@kadira/storybook/dist/server/middleware.js:10:37)
    at Object.<anonymous> (/Users/mdell/Work/Repos/react-redux-starter-app/node_modules/@kadira/storybook/dist/server/index.js:66:34)
```

**Comment by michael-martin** [comment]
Nice catch and fix!
